name: Test - Dispatch
run-name: Test Dispatch - ${{ inputs.param1 }}

on:
  workflow_dispatch:
    inputs:
      param1:
        description: Tag of an existing image
        required: false
        default: ''

jobs:
  init:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
